name: Config Support Request
description: Support for Frigate configuration
title: "[Config Support]: "
labels: ["support", "triage"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the problem you are having
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Visible near the top of the automation UI configuration page in Home Assistant
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Automation config file
      description: This will be automatically formatted into code, so no need for backticks.
      render: yaml
    validations:
      required: true
  - type: textarea
    id: frigate_config
    attributes:
      label: Frigate Config
      description: This will be automatically formatted into code, so no need for backticks.
      render: yaml
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Any other information that may be helpful
