name: Bug Report
description: File a bug report
title: "[Bug]: TitleHere"
labels: ["bug", "triage"]
assignees:
  - sgtbatten
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Also tell us, what did you expect to happen and how you make it happen if you can reproduce in a specific way.
      placeholder: Tell us what you see!
      value: "Something unexpected happened"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the blueprint are you using? Located near the top of the automation UI in Home Assistant.
    validations:
      required: true
  - type: textarea
    id: automation
    attributes:
      label: Automation Config
      description: Please copy and paste your automation config from Home Assistant. This will be automatically formatted into code, so no need for backticks.
      render: yaml
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Other relevant log
      description: please paste the debug log output from the trace if enabled. If you have an error in the home assistant log paste it here. 
      render: yaml
  - type: markdown
    attributes:
      value: |
        After submitting please consider uploading the relevant screenshot of your trace tree/diagram from Home Assistant in the first reply. 
